---
label: Project
hide_body: false
is_partial: false
fields:
- type: number
  name: priority
  label: Priority
  description: Prioritizes the placement in the projects loop.
- type: tag_list
  name: categories
  label: Categories
  description: The category tags for filtering the projects.
- type: select
  config:
    source:
      type: simple
    options:
    - home3
    - image
    - images
    - camera
    - headphones
    - play
    - video-camera
    - pacman
    - bullhorn
    - mic
    - book
    - books
    - file-empty
    - files-empty
    - file-text2
    - file-picture
    - file-music
    - file-play
    - file-video
    - file-zip
    - copy
    - paste
    - folder
    - folder-open
    - price-tag
    - cart
    - coin-dollar
    - coin-pound
    - credit-card
    - phone
    - phone-hang-up
    - envelop
    - pushpin
    - location
    - printer
    - undo2
    - redo2
    - bubble
    - bubbles
    - bubbles2
    - bubble2
    - bubbles3
    - bubbles4
    - user
    - users
    - user-plus
    - user-minus
    - user-check
    - quotes-left
    - quotes-right
    - search
    - cog
    - mug
    - rocket
    - clipboard
    - list-numbered
    - list
    - list2
    - download3
    - upload3
    - sphere
    - earth
    - link
    - attachment
    - happy
    - happy2
    - tongue
    - tongue2
    - grin
    - grin2
    - baffled
    - baffled2
    - confused
    - confused2
    - hipster
    - hipster2
    - blocked
    - cross
    - checkmark
    - checkmark2
    - spell-check
    - play2
    - pause
    - stop
    - previous
    - next
    - backward
    - forward2
    - play3
    - pause2
    - stop2
    - backward2
    - forward3
    - first
    - last
    - previous2
    - next2
    - arrow-up
    - arrow-up-right
    - arrow-right
    - arrow-down-right
    - arrow-down
    - arrow-down-left
    - arrow-left
    - circle-up
    - circle-right
    - circle-down
    - circle-left
    - bold
    - underline
    - italic
    - page-break
    - superscript
    - subscript
    - superscript2
    - subscript2
    - table
    - table2
    - paragraph-left
    - paragraph-center
    - paragraph-right
    - paragraph-justify
    - indent-increase
    - indent-decrease
    - share
    - new-tab
    - embed
    - embed2
    - google
    - google2
    - google3
    - google-plus
    - google-plus2
    - google-plus3
    - hangouts
    - google-drive
    - facebook2
    - twitter
    - rss2
    - youtube
    - youtube2
    - steam2
    - dropbox
    - github
    - wordpress
    - tux
    - appleinc
    - android
    - windows
    - windows8
    - soundcloud
    - soundcloud2
    - skype
    - reddit
    - paypal
    - chrome
    - firefox
    - IE
    - edge
    - safari
    - opera
    - html-five
    - css3
    - git
    - unity
    - gamemaker
    required: true
  default: unity
  label: Icon
  name: icon
  description: An icon to represent the project type.
- type: file
  name: thumbnail
  label: Thumbnail
  description: Displayed in project loop and in sidebar.
- type: text
  name: webm
  label: WebM
  description: Cloudinary path to webm file.
- type: textarea
  config:
    wysiwyg: true
    schema:
      format: markdown
    required: true
  label: Description
  name: description
  description: Short description for project.
- type: text
  name: layout
  label: Layout
  default: project
  description: ''
  hidden: true
  config:
    required: true
pages:
- _projects/places-scraper.md
